### ISSUE TITLE
"Overwrite this receiver" and "Overwrite all receivers" doesn't sync when post edited at receiver

### ISSUE THREAD

**Issue by copperleaf** [GraysonE/data-sync#125]
I created a post called "image handling 111201", sycned it with receiver sites, then modified at https://datareceiver2.copperleaf.dev/

The source site knows the data was modified, but the "overwrite" buttons don't work. It goes through the motions but doesn't removed the added content at receiver2 (which Gordon says it should).

**Comment by GraysonE** [comment]
@copperleaf sorry for the email confusion, this is a legit bug. Will have it fixed shortly.

**Comment by GraysonE** [comment]
@copperleaf done.
