### ISSUE TITLE
Fix content images on receiver sites is in receiver media, but calling from source

### ISSUE THREAD

**Issue by copperleaf** [GraysonE/data-sync#127]
The featured images on the receiver sites pull images appropriately from their local media library, but the content images on receiver sites pull image files from source media library (although they're available in local receiver media library. 

I think this was probably just something we forgot to do. :)

**Comment by GraysonE** [comment]
@copperleaf would you mind using the bug template I made? That way I'm not spending time looking around for what you're talking about. The bug template takes a bit more time to fill out, but it will save both of us time in the long run. :) I actually did code this so it's very likely that the code skipped over something!

**Comment by GraysonE** [comment]
@copperleaf I found this issue happening in "grayson post image." This is indeed a bug and a fantastic catch!

**Comment by GraysonE** [comment]
@copperleaf Fixed!
