### ISSUE TITLE
Post syndicated from source coming in with erroneous category on receivers 

### ISSUE THREAD

**Issue by copperleaf** [GraysonE/data-sync#131]
**Describe the bug**
I've created 2 posts at source that do not have categories noted. When pushed to receiver sites, they come through with categories... inconsistently! 

**To Reproduce**
1. Create a new post at source (title only if you like)
2. Sync to receiver sites
3. Check posts in receiver sites for categories. Receiver1 = star wars, receiver2 = Child , multi1 = star wars, multi2 = star wars

**Expected behavior**
Should not come through with a category on receiver site if no category on source

**Desktop (please complete the following information):**
 - OS: window10
 - Browser Chrome
 - Version ... I don't know, updated yesterday

**Comment by GraysonE** [comment]
**Note**: Term relationships get orphaned after post deletion?
**To Reproduce:**

1. Start fresh
2. Bulk sync
3. Create new post with empty category
4. Sync new post
5. Check for random category addition on receiver site
