### ISSUE TITLE
Post being pushed to excluded receiver site and put in trash

### ISSUE THREAD

**Issue by copperleaf** [GraysonE/data-sync#138]
**Describe the bug**
I created a source post and excluded receiver 1. The post got created in the receiver 1 trash, with a category, and the featured image media synced to the receiver 1 media. 

**To Reproduce**
Create a new post at source with featured image, exclude from at least 1 receiver site
Sync post to other sites
Check excluded site post trash and media - featured image will be in media, associated with post created on receiver site and post will be in the trash with an erroneous category (star wars in the case of receiver 1) 

**Expected behavior**
No media or post will be sent to an excluded receiver site

**Comment by GraysonE** [comment]
@copperleaf not able to reproduce and need more specific instructions. 

1. In all future bug tickets, please specify whether featured image was:
- Added from media library
- Uploaded

2. Please specify which button you press when syncing.
3. A brief overview of what you were testing before this occurred would be nice as well

I've already tested all of these scenarios without reproduction of the bug. Feel free to call me to discuss.
