### ISSUE TITLE
Yoast settings still overwriting receiver settings regardless of post-level override checkbox

### ISSUE THREAD

**Issue by GraysonE** [GraysonE/data-sync#14]
Post name called "Create then exclude" post. That test passed, so I edited the Yoast data (Focus Keyword). That pushed to receiver even on update. I expected it to only be on push, hence the "Override Receiver Yoast Settings" option. So then I edited Focus Keyword on the receiver and re-synced. This triggered the broken link icon (yay!) with message that receiver had updated more recently. Re-pushed by clicking icon. Worked like a charm, except Focus Keyword got overwritten. It should not have.

**Comment by copperleaf** [comment]
**On post creation, Focus Keyword did not transmit from Source to any Receiver.**

On initial update with "Update Yoast settings on receiver with next sync" checkbox UNCHECKED, change to Focus Keyword CORRECTLY did not come thru.  GOOD.

On second update with "Update Yoast settings on receiver with next sync" checkbox CHECKED, CORRECTLY came thru.

**BUG: Yoast Settings should flow to Receiver sites upon initial Publish.**

**Comment by GraysonE** [comment]
@copperleaf Excellent job getting to the source of this bug. Found the solution in record time.
