### ISSUE TITLE
Featured image issues

### ISSUE THREAD

**Issue by copperleaf** [GraysonE/data-sync#148]
**Describe the bug**
1. featured images aren't loading on the back end of the sites (all) so you can't see what image has been selected (but it saves, posts to the front end, syncs out to receivers, etc)
2. All receiver sites are rotating featured images to be landscape even if they're not. 

**To Reproduce**
1. Try to select or upload a new image as a featured image on a post. Notice that it never stops the loading circle of death to show you what you picked. 
2. you've seen this one before.
**Buggy Post**
All sites, all new posts. 
1. Ex: https://multi2.copperleaf.dev/image-to-post-testing-20191126/
2. Ex: https://multi2.copperleaf.dev/wp-admin/post.php?post=139&action=edit

**Which receiver?**
All 

**Testing that was occurring before this test**
1. Has been happening since testing started. 
2, image upload testing - only happens with portrait featured images

**Expected behavior**
1. show me the image
2. don't rotate things

**Comment by GraysonE** [comment]
@copperleaf I'm thinking "Image Rotation Repair" fucked the site up. After reinstalling wordpress core and the data sync plugin, it's working now.
