### ISSUE TITLE
Category detail syndication on posts not working

### ISSUE THREAD

**Issue by copperleaf** [GraysonE/data-sync#149]
**Describe the bug**
When a post is pushed to a receiver site, the category gets created on the receiver site, however the description (native) does not come through. 

I also tried creating a custom field for post categories (see here https://datasource.copperleaf.dev/wp-admin/term.php?taxonomy=category&tag_ID=16&post_type=post&wp_http_referer=%2Fwp-admin%2Fedit-tags.php%3Ftaxonomy%3Dcategory) and when that tries to sync out, it throws a server error on the sync (Post 446, All receivers: Server error encountered.) BUT THEN!!! 

 1. when you check the receiver sites, the category in question is there
 2. on data1 and multi1 (running gutenburg), and multi2 (running classic editor) only the child category "even more custom category" came through, but on data2 (running classic editor) the parent category "custom category" also came through.

 3. when you check the custom **field**, it comes through on all categories (as expected) but the content of the custom field doesn't come through to any site. 

I'm guessing these things might be vaguely related and worth working on at the same time. 

**To Reproduce**
Create a post in a category that has a description
Sync to receivers, check receiver post categories. The category gets created on the receiver but no description comes through. 

If the post category has a custom field associated with it, the receivers can't sync and then have all sorts of issues anyway (see above)

**Buggy Post**
Link to existing post where this issue appeared: 

Here's the post I'm using for testing: https://datasource.copperleaf.dev/wp-admin/post.php?post=446&action=edit

1. https://datareceiver1.copperleaf.dev/wp-admin/edit-tags.php?taxonomy=category - "parent" should have a description that matches the description on source
2. Here's the category with the custom field on source (at the bottom under "something you want") https://datasource.copperleaf.dev/wp-admin/term.php?taxonomy=category&tag_ID=16&post_type=post&wp_http_referer=%2Fwp-admin%2Fedit-tags.php%3Ftaxonomy%3Dcategory) 

here are links to the category pages on each site, just to make your life better. 
https://datasource.copperleaf.dev/wp-admin/edit-tags.php?taxonomy=category
https://datareceiver1.copperleaf.dev/wp-admin/edit-tags.php?taxonomy=category
https://datareceiver2.copperleaf.dev/wp-admin/edit-tags.php?taxonomy=category
https://multi1.copperleaf.dev/wp-admin/edit-tags.php?taxonomy=category
https://multi2.copperleaf.dev/wp-admin/edit-tags.php?taxonomy=category

**Which receiver?**
All 

**Testing that was occurring before this test**
Image testing, but that all went smoothly and we're done with that nonsense.

**Expected behavior**
Categories should carry forward their descriptions, including custom fields, to receiver sites. They should also bring their parent categories or our structure going forward will be a shit show (that's a technical term).

**Comment by GraysonE** [comment]
@copperleaf descriptions for terms now showing up and that bug is resolved. I couldn't replicate the server error. Working on only the child category coming over now. . .
