### ISSUE TITLE
Yoast re-syncing doesn't move all fields AND "override" checkbox doesn't auto turn off

### ISSUE THREAD

**Issue by copperleaf** [GraysonE/data-sync#153]
**Describe the bug**
On initial sync, all yoast settings (including social tab details) sync to receiver sites. If edits are made to the yoast settings and the "override" checkbox is marked, the only field that syndicates is the "focus keyphrase". The following data does not get overwritten on receiver sites: cornerstone content toggle, all facebook and twitter fields on "social tab". 

Additionally, I'm under the impression the "yoast override" checkbox is supposed to turn itself off after syncing. It does not (stays checked). 

**Does the error log have any red error messages?**
nope

**To Reproduce**
Create new post at source, fill out all available fields on all yoast tabs. Sync to receiver sites. Change all fields on source post, check "update yoast settings on receiver next sync" checkbox. Sync sites. Check receiver post - note the only updated field is the "focus keyphrase". 

Check source post (reload if you'd like). Note that override checkbox stays checked. 

**Buggy Post**
Link to existing post where this issue appeared: https://datasource.copperleaf.dev/wp-admin/post.php?post=467&action=edit vs https://datareceiver1.copperleaf.dev/wp-admin/post.php?post=87&action=edit

**Which receiver?**
all 

**Expected behavior**
All yoast fields should syndicate when appropriate (when checkbox is marked to do so) not just the focus keyphrase. 

Checkbox about override on next sync should turn off after next sync.

**Comment by GraysonE** [comment]
@copperleaf fixed the yoast settings not syncing correctly. Auto-disabling yoast overwrites sounds like a nice to have at this point, what do you and Gordon think?

**Comment by copperleaf** [comment]
Gordon says the auto-disable is absolutely critical. What's it going to take to get that working?

**Comment by copperleaf** [comment]
Tested Yoast sync. Working 90% - if you leave a social image field blank on source a "not first time" sync to receiver, the receiver doesn't remove the image: https://datasource.copperleaf.dev/wp-admin/post.php?post=473&action=edit - no facebook image vs https://datareceiver1.copperleaf.dev/wp-admin/post.php?post=94&action=edit facebook image is there

**Comment by copperleaf** [comment]
Turns out anything field left blank at source doesn't update to the receiver after sync. See same links as above.
