### ISSUE TITLE
CTP Taxomony terms don't sync to recievers

### ISSUE THREAD

**Issue by copperleaf** [GraysonE/data-sync#167]
**Describe the bug**
I just created a new CPT Tax "colors" and assigned it to Posts at source. Created a "green" post. Synced post to receivers, the Taxonomy of "colors" came through to appropriate receivers, but the term "green" did not. 

**Does the error log have any red error messages?**
nope

**Buggy Post**
Link to existing post where this issue appeared: 
Source: https://datasource.copperleaf.dev/wp-admin/post.php?post=563&action=edit

Receivers
https://datareceiver1.copperleaf.dev/wp-admin/post.php?post=2&action=edit
https://multi1.copperleaf.dev/wp-admin/post.php?post=2&action=edit
https://multi2.copperleaf.dev/wp-admin/post.php?post=2&action=edit

**Which receiver?**
All that were supposed to receive the post

**Testing that was occurring before this test**
None, new clean installs

**Expected behavior**
Term should come through with post / tax

**Comment by GraysonE** [comment]
@copperleaf had to do with a bunch of old taxonomies still at source. I deleted everything that looked logical to delete. This is closed.
