### ISSUE TITLE
None of the Yoast settings sync to receiver sites anymore

### ISSUE THREAD

**Issue by copperleaf** [GraysonE/data-sync#176]
Looks like something got bumped fixing other things recently. Tried to do final test on Yoast settings and nothing comes through from source: 

https://datasource.copperleaf.dev/wp-admin/post.php?post=640&action=edit (post with settings)
https://datareceiver1.copperleaf.dev/wp-admin/post.php?post=61&action=edit (example receiver post - missing focus keyphrase, cornerstone content toggle "on", Facebook and Twitter titles, descriptions and images.) 

NOTE: images that were uploaded to source for facebook and twitter yoast images did come through to media. 

I know this use to work.

**Comment by GraysonE** [comment]
Fixed from commit 463d9acbcaa3e4838de12a68fd73d11278b76324. Close issue
