### ISSUE TITLE
Receiver sync not working in real environments

### ISSUE THREAD

**Issue by copperleaf** [GraysonE/data-sync#182]
**Describe the bug**
I set up the site that will be LIVE source and connected it to staging environments of live sites we'll actually be connecting to. When trying to push my first post from source to the staging environment receivers, the sync page notes there are no enabled post types on any receiver, but I set them up to receive posts. 

I'm hoping there's something easy I missed in set up. Could you take a look? You're set up as an admin on all relevant sites. Please let me know what I missed or what the bug is. 

Live source: 
http://dataapisourcev.kinsta.cloud/wp-admin/admin.php?page=data-sync-options

Receivers:
https://palmbeaches.staging-atlantismu.kinsta.cloud/wp-admin/admin.php?page=data-sync-options
https://coralsprings.staging-atlantismu.kinsta.cloud/wp-admin/admin.php?page=data-sync-options
https://lifeprogram.staging-atlantismu.kinsta.cloud/wp-admin/admin.php?page=data-sync-options
https://atlantisacademy.staging-atlantismu.kinsta.cloud/wp-admin/admin.php?page=data-sync-options
https://staging-spectrumschoolscom.kinsta.cloud/wp-admin/admin.php?page=data-sync-options

**Comment by GraysonE** [comment]
This was an issue with SSL. Source API wasn't set up as https.

**Comment by copperleaf** [comment]
All sites have SSLs in place. Receiver sites continue to turn off all enabled post types each time source tries to sync. 

https://source.copperleaf.dev/

https://atlantis.atlantis.copperleaf.dev/wp-admin/
https://coralsprings.atlantis.copperleaf.dev/wp-admin/
https://lifeprogram.atlantis.copperleaf.dev/wp-admin/
https://palmbeaches.atlantis.copperleaf.dev/wp-admin/
https://spectrum.copperleaf.dev/wp-admin/

Please check by enabling "post" on receiver sites, creating a new post at source and trying to sync. The data sync at source tells me there are no enabled post types on all receivers. Receivers note no enabled post types. Even after they've been turned on. 

Stream plugin notes that the setting has been changed when I turn them on, but no record of them getting turned off.
