### ISSUE TITLE
Multisite compatibility

### ISSUE THREAD

**Issue by copperleaf** [GraysonE/data-sync#27]
Data API needs to be able to interface with Receiver sites that are multisite sub-sites.  I _think_ this is just a matter of finding one or two multisite functions that will wrap your existing stuff to catch if a sub-site is multisite more or less automatically.  However, I'm not _exactly_ sure what functions those are.  

Here's a place to start:
get_blog_id_from_url
https://codex.wordpress.org/Function_Reference/get_blog_id_from_url

- [x] Network activation db tables
- [x] check correct table prefix
- [x] Check correct upload directory
- [x] Terms not syncing
- [x] Templates not syncing

**Comment by GraysonE** [comment]
@copperleaf remember on the right to add assignees, labels, and the project. I have some automation set up to do some fancy stuff once the proper metadata is added.

**Comment by copperleaf** [comment]
👍

Gordon
@CopperGordon


*Copper Leaf Creative*(970) 776-8778
446 E 29th St. #2012
Loveland, CO 80539
www.copperleafcreative.com

*I do not check email  until 2:00 PM daily.  If you need something
time-sensitive before that, please email Leah@copperleafcreative.com
<Leah@copperleafcreative.com>*

In case of Urgency, please call (970) 776-5021 and leave a message.  We'll
return your call as soon as humanly possible.

*We are in Mountain Time and typically in the office 9:00 AM - 5:00 PM*

**Comment by GraysonE** [comment]
- [ ] Network activation db tables

- [ ] check correct table prefix

- [ ] Check correct upload directory

**Comment by GraysonE** [comment]
@copperleaf Gordon, for some reason I can't access the sub sites on this multi-site. I can't get to their dashboards. Can you help me out?

**Comment by copperleaf** [comment]
I'm running into the same thing.  I'll get it figured out and let you know.

Gordon
@CopperGordon


*Copper Leaf Creative*(970) 776-8778
446 E 29th St. #2012
Loveland, CO 80539
www.copperleafcreative.com

*I do not check email  until 2:00 PM daily.  If you need something
time-sensitive before that, please email Leah@copperleafcreative.com
<Leah@copperleafcreative.com>*

In case of Urgency, please call (970) 776-5021 and leave a message.  We'll
return your call as soon as humanly possible.

*We are in Mountain Time and typically in the office 9:00 AM - 5:00 PM*

**Comment by copperleaf** [comment]
Fixed.  You should be able to log in now.

Gordon
@CopperGordon


*Copper Leaf Creative*(970) 776-8778
446 E 29th St. #2012
Loveland, CO 80539
www.copperleafcreative.com

*I do not check email  until 2:00 PM daily.  If you need something
time-sensitive before that, please email Leah@copperleafcreative.com
<Leah@copperleafcreative.com>*

In case of Urgency, please call (970) 776-5021 and leave a message.  We'll
return your call as soon as humanly possible.

*We are in Mountain Time and typically in the office 9:00 AM - 5:00 PM*

**Comment by GraysonE** [comment]
@copperleaf I still can't access the sub sites. Am I an idiot?
![Screen Shot 2019-09-11 at 3 08 26 PM](https://user-images.githubusercontent.com/7062755/64735613-1f854c80-d4a6-11e9-9ebf-37fff056d349.png)

**Comment by GraysonE** [comment]
@copperleaf looks like site urls was defaulting to http btw. I just went in and fixed them in the db.
