### ISSUE TITLE
List Sites Not Synced

### ISSUE THREAD

**Issue by GraysonE** [GraysonE/data-sync#3]

**Comment by copperleaf** [comment]
In details, sites shown as excluded.  Good!

...However it's inaccurate.  Bad!

Look at "Constant Comment" Tea post.  It is set to exclude from Multi 2.  It says "This post is excluding this receiver.", however, the post appeared on Multi 2.  

Tried again with just excluding Single sites (to remove potential multisite confounding factor).  Still, only 1 of the excludes was excluded.  Probably a loop problem?

**Comment by copperleaf** [comment]
Also, after sync details still return "Unsynced. Please check connected site info or logs for more details."

See post "Exclusionary Test"

**Comment by copperleaf** [comment]
Still looking at Exclusionary Test Tea post, I turned off sync for Tea on Receiver 1.  Source showed the change under Connected Sites.  However, this caused the Status widget to show Receiver 1 as "Unsynced".  I synced.  Sync re-enabled Tea as an enabled post on the Receiver.  

[~28:00 Bugs 3 Recording 4]

Status still returning "Unsynced. Please check connected site info or logs for more details."  No errors in log.  

**BUGS:** 
1.  When multiple sites are selected to be excluded, only one of them is actually excluded.
2.  Status widget doesn't appear to have proper awareness of a Receiver site not accepting that post type.
3.  Probably related to #2, Status widget gives (apparently) incorrect status of "Unsynced"
4.  Doing a regular Sync changes the "enabled post types" setting on Receiver sites.  It should not.

**Comment by GraysonE** [comment]
- [ ] When multiple sites are selected to be excluded, only one of them is actually excluded.

- [ ] Status widget doesn't appear to have proper awareness of a Receiver site not accepting that post type.

- [ ] Probably related to #2, Status widget gives (apparently) incorrect status of "Unsynced"

- [ ] Doing a regular Sync changes the "enabled post types" setting on Receiver sites. It should not.

**Comment by GraysonE** [comment]
@copperleaf 4 is a setting that can be changed, so I'm going to skip it. I just fixed the first which in turn fixed two and three!
