### ISSUE TITLE
Incorrect "A receiver post was updated after the last sync."

### ISSUE THREAD

**Issue by copperleaf** [GraysonE/data-sync#51]
After reset then initial sync, 3 posts (ID's 53, 20 ,15) all showed "A receiver post was updated after the last sync." However, this is obviously not true as they were just synced.  

Are you comparing the Last Updated field from Source Post to Receiver Post?  If so, this will always be in the future for receiver sites.  Instead it should check Last Sync vs. Last Updated on Receiver.  (Maybe you're already doing this right and the problem is somewhere else.)

**Comment by GraysonE** [comment]
@copperleaf you're right, what I need to do is two checks: check the receiver updated time vs. synced time and the source updated time vs. synced time

**Comment by copperleaf** [comment]
Looks good.
