### ISSUE TITLE
Canonical not set

### ISSUE THREAD

**Issue by copperleaf** [GraysonE/data-sync#52]
[9:30 in Recording 2]

Canonical not set in Receiver 2 (should have URL for Receiver 1)

Other notes:
- When post was initially created, first sync stalled out because Canonical was not set.  This should be solved by implementing the JS error upon post save to make this field required.  

- I set Canonical, saved, and re-synced.  Response was "Partially Synced" - Partially syndicated. Some posts may have failed to syndicate with a connected site. Please check connected site info or logs for more details.  Status for both rows was "Synced on this connected site".  No errors in log look related (just two about post thumbnails for other posts not updating)

**Comment by GraysonE** [comment]
@copperleaf this should be fixed now that the canonical JS check is working.

**Comment by copperleaf** [comment]
Canonical JS catch is confirmed working.  That Issues is moved to "completed" column.

Also can confirm **canonical is not set upon Publish** but is upon Update.  (Your post title was a very handy note about this.)  Moving this back into Developing.
