### ISSUE TITLE
Selecting Canonical / Excluded Site on Site Not Enabled for Sync - Send UI Notification

### ISSUE THREAD

**Issue by GraysonE** [GraysonE/data-sync#8]
Red UI notification

**Comment by copperleaf** [comment]
Excellent!  ... but I think it would be better if this was a JS catch like Canonical not being checked at all.  

To clarify, this error: "This post's canonical URL is pointing to a receiver that is excluded." can remain in the Dashboard Widget, but should ALSO be a JS catch when saving the post itself.  

Similarly, if it's possible to catch if a site isn't enabled for sync ... 
... WAIT ... 
Is it possible to only offer sites with the post type enabled in the __options__ for Canonical?  That would bypass the need to validate the selection if we only offered valid options.

**Comment by GraysonE** [comment]
@copperleaf I think keeping this as a UI notification will be best because there is too much work required to validate the post's excluded sites and every receiver post type within the post before the post has synced, sites have been connected, sites are connected and the post is synced, or several other scenarios. It's easier to check it in one place. However, I agree the UX would be better the way you suggested. I think it's more important to get this finished the way it currently works with a better UI notification.

**Comment by GraysonE** [comment]
@copperleaf I added the js alert into the post to catch canonicals pointing to an excluded site.
