### ISSUE TITLE
Featured Image not arriving at Receiver

### ISSUE THREAD

**Issue by copperleaf** [GraysonE/data-sync#83]
For post "Featured Image & Excluded Site" the featured image did not arrive at any of the Receiver sites.  It is not in Media.

When this is fixed, check Issue #58 as well.

///////////  MORE!

Totally new media added to Source syndicates successfully.  

If media gets altered (deleted) on ANY receiver site, all Featured Image associations are lost.

**Comment by GraysonE** [comment]
@copperleaf this one is super weird. I changed the featured image and it didn't sync. I added a featured image on a different post which had a media item that was already attached to a different post and it didn't "attach" but showed as a featured image (I'm assuming it pulls this from post meta). So I went into the media gallery and attached a random image to a post that had an existing featured image. Now, there is a different featured image displayed on source than the receiver after push. On the receivers, the image I attached via media gallery showed up as the featured image. On source, it's the featured image I manually changed in the post itself. Yes, confusing. I hope I communicated this clearly. . . Do you have any idea why this is happening? I've never encountered this before and I'm assuming it's some sort of wordpress functionality I'm not familiar with.
